/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Breadcrumbs: typeof import('./src/components/Breadcrumbs.vue')['default']
    Card: typeof import('./src/components/Card.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Search: typeof import('./src/components/Search.vue')['default']
  }
}
